[package]
name = "invaders"
description = "A Space Invaders game TUI"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
repository = "https://github.com/mattdowdell/invaders"
license = "MIT"
categories = ["command-line-utilities", "games"]
keywords = ["games", "tui", "space invaders"]

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
crossterm = "0.22"
home = "0.5.3"
rand = "0.8.5"
tui = "0.17.0"
