name: release
on: workflow_dispatch

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          #- macos-11
          - ubuntu-20.04
          #- windows-2019
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      # TODO: move to separate job but archive artifacts
      - run: cargo install cargo-get
      - run: git tag -a $(cargo get version --pretty) -m "Version $(cargo get version)"
      
      # debugging
      - run: ls -alph
      - run: git tag --list -n1
      - run: git remote -v
      
      - run: git push origin $(cargo get version --pretty) --dry-run
      
      # TODO: create draft release
      # TODO: add compressed binaries to release
